version: '3.8'

services:
  # Development service
  bimeh-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_UPLOAD_BASE_URL=${NEXT_PUBLIC_UPLOAD_BASE_URL}
      - NEXT_PUBLIC_AUTH_API_URL=${NEXT_PUBLIC_AUTH_API_URL}
      - NEXT_PUBLIC_PET_API_URL=${NEXT_PUBLIC_PET_API_URL}
      - NEXT_PUBLIC_USER_API_URL=${NEXT_PUBLIC_USER_API_URL}
    command: npm run dev
    profiles:
      - dev

  # Production service
  bimeh-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_UPLOAD_BASE_URL=${NEXT_PUBLIC_UPLOAD_BASE_URL}
      - NEXT_PUBLIC_AUTH_API_URL=${NEXT_PUBLIC_AUTH_API_URL}
      - NEXT_PUBLIC_PET_API_URL=${NEXT_PUBLIC_PET_API_URL}
      - NEXT_PUBLIC_USER_API_URL=${NEXT_PUBLIC_USER_API_URL}
    restart: unless-stopped
    profiles:
      - prod
